### ISSUE TITLE
"Save Image As" results in black image

### ISSUE THREAD

**Issue by FedPete** [notchris/phaser3-bitmapfont-generator#2]
Canvas "Save Image As" in Firefox 75.0 (64bit), Window 7, does not work, because saved image is a black (canvas) square. No problems found on Chrome.
Even when using a different font color that black. The outcome is still a black sqare, while the correct bitmap font is displayed on screen using a white canvas.

**Comment by notchris** [comment]
@FedPete Thank you for catching this, I will add a button in the next version that generates the image and initiates a download without having to use the context menu.

**Comment by notchris** [comment]
I think this is now updated in the latest merge.
